### ISSUE TITLE
Merging #95 did not update the website

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/oscar-website#100]

**Comment by rfourquet** [comment]
Oh, it did for me... could it be a "cache" (webpage cached by the webbrowser) problem ? can someone else check that? (visit the "macOS 10.12 or newer" section at https://oscar.computeralgebra.de/install/, and check if there is a paragraph starting with "Note: some users have experienced build failures on macOS 10.15").

**Comment by fingolfin** [comment]
It was broken on the server, I fixed it now -- the daemon was not running. Will figure out why now, but for now, the website should update. Let's make sure that whenever anyone merges a PR, that we then also check a minute later that it became visible. (In this case, I think it was me who neglected to do that!)

**Comment by rfourquet** [comment]
Ok thanks, I will also try to remember to check for every merged PR, even when I'm not merging myself.

**Comment by fingolfin** [comment]
Just to explain what happened: the webserver rebooted, and the systemd services I set up to restart the website were not restarted as well. Reason: I had forgotten to "enable" them -- which is separate from "starting" them, and ensures they are reloaded after a reboot. (Don't get me wrong, I think this makes sense; I must say after all negative things I read on Hackernews and elsewhere about systemd over the past couple years, now actually using it for the first time I find it quite pleasant and well-documented; I actually had read the bit about having to "enable", and simply forgot to do it once my testing was done. I.e. blame here is on me, not systemd)

**Comment by fingolfin** [comment]
Thanks @rfourquet much appreciated!
