### ISSUE TITLE
Add more example notebooks

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#111]
I think all examples that are tested on https://oscar-system.github.io/oscar-ci-status/ should also be shown on the website in the examples (@micjoswig @fieker @wdecker can speak if they disagree).

@rfourquet please take care of that; there are links to the notebook in this CI dashboard, but you can also ask @rbehrends about where to find them etc. Probably also a good if @rbehrends notifies @rfourquet (and vice versa) about new examples?

**Comment by rbehrends** [comment]
I added a PR for the new GIT-Fans notebook just recently, so @rfourquet should already have that information.

With that, I think that the only one missing is the tropicalization notebook and I don't know its status. I added it to the CI tests on my own when I saw it, but I don't know if it is in its final state.

**Comment by rfourquet** [comment]
> the only one missing is the tropicalization notebook and I don't know its status

@micjoswig should this notebook be added to the website?
(for reference, it's currently at https://github.com/micjoswig/oscar-notebooks/blob/master/patchworking/Tropicalization.ipynb)

**Comment by rfourquet** [comment]
@rbehrends There is [GroebnerBasis.ipynb](https://github.com/ederc/GroebnerBasisNotebooks/blob/master/GroebnerBasis.ipynb) added recently to the website which I don't see on CI.

There is also the recent "Decomposition of Binomial Ideals", but it probably won't work yet on CI (it depends on 4ti2, but I don't know the details).

**Comment by micjoswig** [comment]
Yes, please!  Thanks, Rafael.  -- Michael

On 20.05.20 15:49, Rafael Fourquet wrote:
>> the only one missing is the tropicalization notebook and I don't know its status
> 
> @micjoswig should this notebook be added to the website?
> (for reference, it's currently at https://github.com/micjoswig/oscar-notebooks/blob/master/patchworking/Tropicalization.ipynb)
> 

-- 
Prof. Dr. Michael Joswig           <joswig@math.tu-berlin.de>
Technische Universitaet      Institut fuer Mathematik, MA 6-2
Str. des 17. Juni 136                 D-10623 Berlin, Germany
phone +49 (30) 314-75904               fax +49 (30) 314-25047

**Comment by rbehrends** [comment]
I've added the GroebnerBasis notebook to the CI tests.

**Comment by rfourquet** [comment]
I will close this issue, as this is mostly resolved. When a new notebook is added on the website, I will try to remembed to check that it's on CI or ping @rbehrends. And conversely, Reimer please ping me if a new notebook is added on CI (for example with a message in this issue).
