### ISSUE TITLE
Add instructions to install Oscar in a docker container running ubuntu

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/oscar-website#120]
I suggest adding the following instructions to prepare a docker container running Ubuntu (`ubuntu:latest`) for installing `Oscar`:

In the container run
```bash
apt-get update
apt-get install curl wget autoconf make g++ julia libjulia-dev
```

**Comment by rfourquet** [comment]
I'm not familiar with docker containers, but are these instructions specific to such containers or more generally to `ubuntu:latest` ?
In the install page, we already have instructions for `Ubuntu 18.04` or newer (containing only `apt-get install build-essential`): doesn't it work in a container, or are these instructions intended as shortcut for both steps 1. (pre-requesites) and 2. (Julia) ?

**Comment by mohamed-barakat** [comment]
At least on `ubuntu:latest` you need besides the packages `build-essential` (Step 1) and `julia` (Step 2) also

1. one of the packages `curl`, `wget`, `fetch`, `busybox` (yet missing in Step 1)
2. `libjulia-dev` (yet missing in Step 2)

Besides, in a container, you are usually root and `sudo` is not available by default.

**Comment by mohamed-barakat** [comment]
By the way:
```
GAP.Packages.install
```
requires `wget` to be installed.

**Comment by fingolfin** [comment]
Using Docker is not a primary focus for us anymore, definitely not something we wish to suggest to regular users.
