### ISSUE TITLE
add NEWS for GroebnerBasis.jl

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/oscar-website#121]
@ederc Would be be willing to add a news item for the 0.1.0 release of GroebnerBasis.jl?
(cf. https://github.com/oscar-system/oscar-website#how-to-contribute-a-news-post).

Also `GB.jl` has been renamed to `GroebnerBasis.jl` right? If so I will update the website accordingly.

**Comment by fingolfin** [comment]
@ederc ping?
