### ISSUE TITLE
add NEWS for HomalgProject

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/oscar-website#122]
HomalgProject.jl doesn't appear in the homepage of the website, but is mentioned in the documentation and community pages, maybe a News item is warranted for its releases? cc @mohamed-barakat

**Comment by mohamed-barakat** [comment]
Thanks, I will prepare a PR for the next release in the coming days.

**Comment by mohamed-barakat** [comment]
We will manage the `Oscar` dependency in steps. `HomalgProject` will give up the `Singular` dependency and a new package will gradually include the dependency of the various `Oscar` components. We are still discussing the name of the new package that will be hosted on `oscar-systems`.

**Comment by fingolfin** [comment]
@mohamed-barakat whats's the status of this?

**Comment by mohamed-barakat** [comment]
I have a principal agreement with Sebastian Posur, but didn't find the time yet to split the package. In any case, `HomalgProject.jl` will depend only on `GAP.jl`. Then a new package `hCAP.jl` will depend on `Singular.jl` and a third package `hCAPWithOSCAR.jl` will depend on the entire `Oscar.jl`.
