### ISSUE TITLE
Example page looks corrupted on brave browser

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/oscar-website#124]
![image](https://user-images.githubusercontent.com/871986/82449354-6272d780-9aab-11ea-8493-9250379125b3.png)

**Comment by rfourquet** [comment]
It also happened to me once (on firefox I think), but reloading the page solved the problem. Does it solve it for you? I just tried with the brave browser and got a correct rendering at first try.

**Comment by mohamed-barakat** [comment]
No it didn't solve it.

**Comment by rfourquet** [comment]
Could you give the version number? (found in the "about" page). 
For reference, I tried with these versions:

> Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
> Version 1.5.123 Chromium: 80.0.3987.163 
> Version 1.1.23 Chromium: 79.0.3945.88

Could someone else [try it](https://oscar.computeralgebra.de/example/), and also report the OS and version number?

**Comment by mohamed-barakat** [comment]
Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by fingolfin** [comment]
Try shift-reload or option-reload or whatever chrome uses for a "force reload". That fixed it for Wolfram

**Comment by fingolfin** [comment]
https://superuser.com/a/278393

**Comment by mohamed-barakat** [comment]
Aaaaah, excellent. Thanks. I will close this issue.
