### ISSUE TITLE
install.md: re-enable "Starting GAP with JuliaInterface" ?

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/oscar-website#132]
At the end of install.md, there are commented out GAP-related instructions:
```
~/.julia/gap.sh
```
and
```
LoadPackage( "JuliaInterface" );
```
Can this TODO be done, now that the issue is closed?

> TODO: disabled until https://github.com/oscar-system/GAP.jl/issues/335 is resolved

On my system this file "~/.julia/gap.sh" is not present.

cc. @fingolfin

**Comment by fingolfin** [comment]
Resolved in a different way (by explaining about `GAP.prompt()`) in 531aa05290e6c8c9f62bd14c35aa9d406e498bff
