### ISSUE TITLE
Add "Computing polynomial bases 1" notebook

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/oscar-website#138]
The notebook at
https://nbviewer.jupyter.org/github/johannesflake/polybases-examples/blob/master/polybases-ex-1.ipynb
has been provided by Johannes Flake and shall be added to the Examples page.
Apart from the repository, the entry for `_data/examples.yml` can be as follows.
```
- title: "Computing polynomial bases 1"
  repository: ...
  filename: polybases-ex-1
  author: Johannes Flake
  thumbnail: oscar.png
  language: julia
```

**Comment by rfourquet** [comment]
I will add this notebook (#139). In the second paragraph, there is a small typo:

> Let's start with the module for the highest weight whose coordinates in terms if the fundamental weights are 

Should be "in terms of"

**Comment by johannesflake** [comment]
Thank you very much for spotting this, Rafael!

A corrected version is available here:
https://nbviewer.jupyter.org/github/johannesflake/polybases-examples/blob/master/polybases-ex1.ipynb?flush_cache

**Comment by johannesflake** [comment]
I am sorry: in fact, there was another, more important mistake: the title should read "Computing monomial bases 1" (even though the package's name is polybases -- it uses polymake). So I guess the entry should be
```yml
- title: "Computing monomial bases 1"
  repository: ...
  filename: polybases-ex-1
  author: Johannes Flake
  thumbnail: oscar.png
  language: julia
```

The updated notebook should be here:
https://nbviewer.jupyter.org/github/johannesflake/polybases-examples/blob/master/polybases-example-1.ipynb
even though for me, currently, nbviewer would not want to update its cache.

**Comment by rfourquet** [comment]
> So I guess the entry should be

I updated the title accordingly in #139, and also the filename to `polybases-example-1` according to your nbviewer link. 

I will merge once nbviewer can display the notebook.

**Comment by johannesflake** [comment]
Yes, thank you very much also for fixing the file name.
Apparently, the link works now.
