### ISSUE TITLE
Our Slack should be mentioned on website

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#149]
... on https://oscar.computeralgebra.de/community/ with brief explanation what it is / what is good for, and how to join (right now that means: "please email to... (??? perhaps me?) and we'll give you an invite. We'd like to automate this but this is a bit tricky"

@rfourquet can you prepare a draft for such a thing?

**Comment by fingolfin** [comment]
We should also expand the "How to contribute" text: right now it just says something like "fork and submit a PR". But in reality, we also want to have them interact with us, ideally beforehand. So let's insert something to that effect:

> Contributions are welcome. If you want to contribute to OSCAR, you can simply fork the repository you want to contribute to and provide a pull request. We recommend that you also (or possibly beforehand) get in touch to avoid duplication of efforts; we'll also be happy to talk to you about design decisions, help you figure out how to do things etc.

@fieker @micjoswig may also have thoughts about this

**Comment by fieker** [comment]
On Fri, Jan 15, 2021 at 06:52:51AM -0800, Max Horn wrote:
> We should also expand the "How to contribute" text: right now it just says something like "fork and submit a PR". But in reality, we also want to have them interact with us, ideally beforehand. So let's insert something to that effect:
> 
> > Contributions are welcome. If you want to contribute to OSCAR, you can simply fork the repository you want to contribute to and provide a pull request. We recommend that you also (or possibly beforehand) get in touch to avoid duplication of efforts; we'll also be happy to talk to you about design decisions, help you figure out how to do things etc.
> 
> @fieker @micjoswig may also have thoughts about this
> 

We also need to add/ update the Oscar vs Julia issue...

**Comment by rfourquet** [comment]
> "please email to... (??? perhaps me?) and we'll give you an invite

Maybe the "oscar-webmaster" email?
