### ISSUE TITLE
Add prominent link(s) to the Oscar.jl github

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#157]
It is rather difficult to find links to https://github.com/oscar-system/Oscar.jl on https://oscar.computeralgebra.de/ ; there is one on https://oscar.computeralgebra.de/community/ and that's essentially it.

I suggest two things:

1. Add a "Fork me on Github" decoration on the top right like on https://tmate.io and many other pages
2. add it to the nav menu

**Comment by fingolfin** [comment]
@rfourquet can you please look into this

**Comment by fingolfin** [comment]
Could e.g. use https://forkmeon.github.io for the first one (perhaps instead of "Fork me on GitHub" we want some other text, say "Visit us on GitHub" or "Go to the code repository" or so? Depends a bit on the target crowd, I guess.

**Comment by rfourquet** [comment]
I was playing with https://codepo8.github.io/css-fork-on-github-ribbon/ by pasting the CSS code in the index.md file, but can't yet get a satisfactory result. And indeed, I'm not personally really convinced that a "Fork me on GitHub" banner is desirable on the landing page; but sure it's familiar for developers.

**Comment by rfourquet** [comment]
> Could e.g. use https://forkmeon.github.io 

This one works fine indeed.
