### ISSUE TITLE
Meeting pages: improve top nav bar

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#227]
On meeting pages like https://oscar.computeralgebra.de/meetings/2022-02/ we should a nav bar at the top for the various subpages. This could be improved in various ways:
- highlight the currently active page
- render it nicer
- allow for an order other than alphabetical (?)

**Comment by fingolfin** [comment]
First work was done in PR #377 but some tweaking would be good; see also the comment I left there

**Comment by aaruni96** [comment]
From @fingolfin :

> So it looks like this now for me: <img width="832" alt="Screen Shot 2024-10-25 at 14 38 50" src="https://github.com/user-attachments/assets/87b59f4e-8892-4714-90e8-bcb5b6ec652f">

> Some remarks: instead of an "aqua" box to highlight current selection, perhaps simply change it to bold face?

> And the gray next to gray isn't too nice. Maybe try orange, e.g. #fab914 and then change the link color *in the top bar only* from blue to black?

**Comment by aaruni96** [comment]
Does this look any better, @fingolfin ? We tried `#fab914`, but it looked too bright/shiny/harsh/in-your-face (@HereAround and I can't agree on the right word). We also tried the "oscar yellow" from the text "symbolic tools" in the oscar logo, but didn't like it.

The blue is `#a9ddf7`


![image](https://github.com/user-attachments/assets/50e03475-2328-4bc5-a592-bc498d4633ae)

**Comment by fingolfin** [comment]
Thank you it is much better now. Some remaining requests:
1. when I am on the landing page for a meeting, nothing is highlighted (bold) in the "subnavigation". Perhaps the title of the meeting should be bold then? Or perhaps the landing page could be represented in the list of subpages (e.g. first item "Overview" or so)
2. there is more vertical white space above the headline "OSCAR workshop" on the landing page than on e.g. the "Participants" page (see Aaruni's screenshot in the preceding comment). This is IMHO better, resp. on "Participants" (and the other subpages) there is too little vertical white space there.
3. In addition I would reduce the vertical blue space below the subnav a bit (say from `padding-bottom: 40px` to `20px`. Then it looks better balanced to me.

**Comment by fingolfin** [comment]
I am very happy with this now. Thank you!!
