### ISSUE TITLE
Documentation: Installation under Windows

### ISSUE THREAD

**Issue by ulthiel** [oscar-system/oscar-website#244]
I have managed to install Julia under Windows as described in the documentation. I have minor suggestions to make things more clear:

In the first item it is said: Search for "Turn Windows features on or off". I first wondered: search where? Maybe you could add to search in this task bar thingy, whatever the correct name is. Is there a keyboard shortcut for the search?

In item 5 you it is said: Click the Windows store icon. I had to search for this as well, there was no shopping bag (maybe I removed it already, I can't remember).

I use Windows 11 and my installation wasn't that old but after starting Ubuntu from the App Store I received an error message telling me I need WSL2. It came with a link to https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package. So maybe this should be added as another step.

Edit: Search shortcut is Windows Key + S and the thingy is indeed called taskbar ([reference](https://support.microsoft.com/en-us/windows/search-for-anything-anywhere-b14cc5bf-c92a-1e73-ea18-2845891e6cc8#ID0EDF=Windows_11)).

Edit: I ran into a pitfall when doing `apt-get update` as described in the installation step 1 for Ubuntu. It said "Release file...not ready yet". With some googling I found [this](https://askubuntu.com/questions/1096930/sudo-apt-update-error-release-file-is-not-yet-valid): the clock in WSL2 seems to be wrong sometimes. This can be fixed with `sudo hwclock --hctosys `. After that, the installation worked.

**Comment by fingolfin** [comment]
Thanks for the feedback. Unfortunately few OSCAR developers use Windows, so we are dependent on reports or even better, PRs, by people who do know WSL in order to improve the instructions.

I think there is a completely different way to install WSL these days, by following https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by fingolfin** [comment]
I am going to transfer this to the website repository

**Comment by fingolfin** [comment]
See also issue #220

**Comment by ulthiel** [comment]
Oh, sorry, didn't know there was an extra repository. And the WSL instruction you link look good. I didn't really like the App Store thing. Anyways, the instructions worked and this is very good already.

**Comment by HereAround** [comment]
I believe this can be closed, since the installation page already gives detailed instructions for windows (cf. https://www.oscar-system.org/install/).
