### ISSUE TITLE
Install instructions should use apt

### ISSUE THREAD

**Issue by paemurru** [oscar-system/oscar-website#316]
The [install instructions](https://www.oscar-system.org/install/) for Ubuntu or Debian should use `apt`, not `apt-get`. The [Debian manuals](https://www.debian.org/doc/manuals/debian-handbook/sect.apt-get.en.html) say "The most recommended interface, apt, is the one that we will use in the examples given in this section".

**Comment by fingolfin** [comment]
Thanks. Resolved by 7570a5a18b2bab1dcadf7a2c115342212c8409e1 (BTW there is an "Edit this page" link on every OSCAR website page that makes it easy to submit a PR with a suggested change in most cases. For future minor edits that may be more time efficient than talking about it on Slack and opening an issue ;-) )
