### ISSUE TITLE
Tutorials: automate last modified

### ISSUE THREAD

**Issue by aaruni96** [oscar-system/oscar-website#329]
Automatically grab the "last modified" from somewhere at build time. This will the second PR one has to make whenever updating the tutorial.

**Comment by aaruni96** [comment]
I appear to not have rights to assign people or labels in this repo. I would assign this to myself, and label it as "tutorials"

**Comment by HereAround** [comment]
> I appear to not have rights to assign people or labels in this repo. I would assign this to myself, and label it as "tutorials"

Done.
