### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by HereAround** [oscar-system/oscar-website#342]
https://www.oscar-system.org/tutorials/. Then the links created by clicking on the filters seem to be broken. E.g. a click on the blue icon for FTheoryTools leads to https://tutorials/FTheoryTools/.

cc @aaruni96

**Comment by HereAround** [comment]
I just tried the website locally, and then those links work for me. Also, I am under the impression that these links works a couple weeks back.

**Comment by aaruni96** [comment]
The problem appears to be that if you relative link with "/", it goes to website root, but if you relative link with "//", it assumes its a separate website. Should be fixed by #343 .

**Comment by aaruni96** [comment]
> Also, I am under the impression that these links works a couple weeks back.

Was most likely broken by #340 (worked on my test server, didn't check the actual website after deployment)
