### ISSUE TITLE
Broken links and other observations

### ISSUE THREAD

**Issue by HereAround** [oscar-system/oscar-website#346]
I use this issue to collect my observations regarding the website. This may need to be restructured eventually.

All links on https://www.oscar-system.org/meetings/ broken (but the one pointing to the SFB-meetings at the very bottom). E.g. https://www.oscar-system.org/https://www.oscar-system.org/meetings/2023-09/ when I click on "Meeting 09/2023".

**Comment by HereAround** [comment]
cc @aaruni96

**Comment by HereAround** [comment]
I just found another strange link (I am going through the entire website now):

https://www.oscar-system.org/news/

Then click on "OSCAR news atom feed". Is this desired?

**Comment by aaruni96** [comment]
Yeah, I think that one is working as intended. Its the raw feed for people to subscribe to updates via atom ( https://en.wikipedia.org/wiki/Atom_(web_standard) )

**Comment by HereAround** [comment]
Maybe the link to the `AbstractSolving` documentation (as listed here https://www.oscar-system.org/documentation/) should point to https://algebraic-solving.github.io/?

**Comment by HereAround** [comment]
Also, the `homalg_project` is not emcompassed by OSCAR. Remove the links at
* https://www.oscar-system.org/documentation/
* https://www.oscar-system.org/community/

I wonder if also OSCAR.jl should be removed from the list at the bottom of https://www.oscar-system.org/documentation/. After all, the links to the OSCAR documentation are at the top of that page (and highlighted so).

**Comment by HereAround** [comment]
https://www.oscar-system.org/community/ I find the OSCAR development email as oscar-dev@mathematik.uni-kl.de. Maybe this should be updated to an rptu email eventually?

**Comment by HereAround** [comment]
No talks in 2024? (cf. https://www.oscar-system.org/talks/)

**Comment by HereAround** [comment]
Link to cdd at https://www.oscar-system.org/credits/ is broken. Same for factory, gfanlib and mpir.

**Comment by HereAround** [comment]
I have began to fix at least some of these points here: https://github.com/oscar-system/oscar-website/pull/347

**Comment by HereAround** [comment]
Closed by #347 and #348.
