### ISSUE TITLE
"Call Singular from GAP" notebooks do not work (anymore)

### ISSUE THREAD

**Issue by heiderich** [oscar-system/oscar-website#63]
The code in the notebooks

https://nbviewer.jupyter.org/github/oscar-system/OSCARBinder/blob/master/GAPJulia_Singular_car.ipynb

and

https://nbviewer.jupyter.org/github/oscar-system/OSCARBinder/blob/master/GAPJulia_Singular_blog.ipynb

provided by @ThomasBreuer does not work anymore with recent versions.

**Comment by ThomasBreuer** [comment]
@heiderich Thanks for your message.
There are several issues here.
First of all, the code in the notebooks has to be updated, which is not difficult.
A more serious problem is that I cannot use GAP's JupyterKernel package for running these notebooks:
An older installation of this package runs into a GAP crash as soon as one loads a current version of the JuliaInterface package, and installing JupyterKernel anew does not work at all for me.
Currently it seems not to make sense to offer Jupyter notebooks that rely on the Jupyter kernel for GAP.

**Comment by heiderich** [comment]
Thanks for your reply @ThomasBreuer. I see the problem with the Jupyer kernel for GAP.

My main motivation for looking into these notebooks was to provide test code for OSCAR running in GAP that includes Singular.jl.

After opening this issue I found that some tests are actually available:

https://github.com/oscar-system/GAP.jl/blob/master/pkg/GAPJulia/JuliaExperimental/tst/singular.tst

https://github.com/oscar-system/GAP.jl/blob/master/pkg/GAPJulia/JuliaExperimental/tst/singular_blog.tst

When I understand the test logic correctly, it seems seems that those tests are however not executed if the Singular module for Julia is not available. This makes sense, as GAP.jl probably does not want to depend on Singular.jl. 

I would like to include such tests in https://github.com/oscar-system/oscar-ci and force them to be executed. So I wonder where to test them. Maybe we would like to have a GAP packages analogous to https://github.com/oscar-system/Oscar.jl/ but for GAP. There we could include such tests. What do you think?

**Comment by fingolfin** [comment]
The problem is that the GAP Jupyter interface tries to fork a GAP process; but if GAP is linked against Julia, this is not really possible and results in a crash.

As such, I see little hope to resurrect these, unless somebody is willing to overhaul the GAP-Jupyter interface; but as far as I know, it is completely abandoned.

Therefore I propose that we simply remove these examples.

**Comment by mohamed-barakat** [comment]
I am also in favor of removing these examples.
