### ISSUE TITLE
Add CI tests for the examples

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#77]
The examples we provide, including Jupyter notebooks, should undergo CI tests to ensure they are still working; of course that also means we need to watch out for those CI tests and *fix* notebooks (resp. fix the package(s) that caused the regression.

See also issue #63 ; I also think @ulthiel spotted some broken examples.

**Comment by fingolfin** [comment]
@rbehrends is this resolved now?

**Comment by rbehrends** [comment]
To the extent possible, except for the GAP notebooks, where my understanding is that we still have the fork problem to deal with.

"To the extent possible" = we are tracking output diffs, not just errors, but can't flag diffs as errors, as many rely on randomness and thus do not generate reproducible output.
