### ISSUE TITLE
Update website to show new webmaster email address

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#86]
@rfourquet this is for you (I can't assign it to you yet as you need to accept the invitation to oscar-system first).

**Comment by fingolfin** [comment]
@rfourquet You need to determine how exactly you will do this. One idea would be to add a footer to all pages which says something like `Contact webmaster` and which is simply a mailto link to `oscar-webmaster@mathmatik.uni-kl.de`. Or it could be more elaborate: link to a newly created subpage which first suggests to submit an issue here, and then only gives the email as an alternate. Or something completely different you dream up.

**Comment by rfourquet** [comment]
So I didn't get inspiraton till now, so went with the simple option in #102, i.e. a "Contact webmaster" mailto link.
