### ISSUE TITLE
Suggestion: generate part of install page from a script

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#9]
During GAP Days Fall 2018, @sebasguts @ThomasBreuer and me looked at https://oscar.computeralgebra.de/install/ and noticed that the instructions there are still based on Julia 0.6.3, so not even 0.6.4 and certainly not 0.7/1.0.

Having these instructions in a runnable shell script (which a user could perhaps download) would make it easy to test them; that script could also perhaps be used as part of the generation of an OSCAR Docker image. 

That of course means that now you have to keep that script with the website in sync. So the following suggestion was made: the text on the website could be generated *from that script*. Essentially, comments in the script could be turned into text, and the code between comments into code blocks. That way, the instructions are always in sync with the script, and if the script is used to generate a docker image, also the docker image is automatically in sync. And this way, the instructions are constantly tested, and don't risk getting out of date.

**Comment by mohamed-barakat** [comment]
This is a good idea. Maybe @rbehrends and @heiderich could help with this if such a script could also be part of the CI.

**Comment by fingolfin** [comment]
This is obsolete now, as installing OSCAR now amounts to `Pkg.add("Oscar")`.
