### ISSUE TITLE
Broken link for the Factory software

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/oscar-website#91]
At https://oscar.computeralgebra.de/credits/, the link for Factory is ftp://www.mathematik.uni-kl.de/pub/Math/Singular/Factory, which currently doesn't work (since at least a few days).
I'm not sure who can fix that, so I will tentatively ask @hannes14 ?

**Comment by hannes14** [comment]
On Tue, Apr 21, 2020 at 08:08:17AM -0700, Rafael Fourquet wrote:
> At https://oscar.computeralgebra.de/credits/, the link for Factory is ftp://www.mathematik.uni-kl.de/pub/Math/Singular/Factory, which currently doesn't work (since at least a few days).
> I'm not sure who can fix that, so I will tentatively ask @hannes14 ?
The link to factory is now (as www.maathematik.uni-kl.de does not have
ftp any more):
https://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/Factory

**Comment by rfourquet** [comment]
Thanks!
