### ISSUE TITLE
Come up with a nicer way to display the examples

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#92]
The examples display on https://oscar.computeralgebra.de/example/ does not look so nice. This needs to be improved; and once we have more examples, we must also think about how to make this more accessible. Some thoughts and ideas (to be refined, i.e. none of this is set in stone):
- perhaps the examples could be narrower, but then two side by side? (Perhaps a responsive design with "cards" a bit like on <https://oscar-system.github.io/oscar-ci-status/index.html> could be used?)
- assign "keywords" or "tags" to each example, e.g.:  "GAP, Singular, tropical matroids" which give a rough indication which technologies  and mathematical areas are in the example (@rfourquet shall provide the setup, but others can and should help with determining what tags are appropriate)
- once there are many examples (I wish...) we can think about allowing to filter the displayed examples by tag (e.g. "only show examples with tags "GAP" and "tropical" or so)
- .. more? Not sure

**Comment by fingolfin** [comment]
@rfourquet This will become more pressing as new examples are added. Can you please take a look now?

**Comment by fingolfin** [comment]
@rfourquet I really think we should make each example "card" narrower, and then show multiple of them next to each other -- this could be done dynamically. Let me again point at https://oscar-system.github.io/oscar-ci-status/ which I created in less than an hour of work. The central aspect is https://github.com/oscar-system/oscar-ci-status/blob/master/assets/css/cards.css which has a comment saying where I stole the inspiration. The key is the `grid-template-columns` css selector, and once understood, it's pretty easy to adjust.

**Comment by rfourquet** [comment]
Sure I can try to do that now. I just didn't have a personal insight that this would look better.
