### ISSUE TITLE
Provide workaround for crash with Xcode 11.4 / macOS 10.15

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-website#93]
here are crashes when using CxxWrap on macOS 101.5 with Xcode 11.4, which thus affects Polymake.jl and Singular.jl. Relevant issues:
  - <https://github.com/oscar-system/Oscar.jl/issues/82>
  - <https://github.com/JuliaInterop/CxxWrap.jl/issues/230>

Luckily @benlorenz [came up with a workaround](https://github.com/oscar-system/Oscar.jl/issues/82#issuecomment-611220692).

This should be added to the website until we have a proper fix -> @rfourquet please take care of that, in coordination with Benjamin (who knows the details), and perhaps @mo\, who can test the instructions

Of course once a "proper" fix is available, we then should remove these instructions again.

**Comment by benlorenz** [comment]
We will need to update this section very soon for CxxWrap 0.10 as the override mechanism changes from the environment variable to Overrides.toml, see [here](https://github.com/JuliaInterop/libcxxwrap-julia#using-the-compiled-libcxxwrap-julia-in-cxxwrap).

Also, the version of libcxxwrap-julia that we clone might need to be updated for every (maybe even minor) CxxWrap release. CxxWrap 0.10.1 uses libcxxwrap-julia 0.7.0, but 0.7.1 is already in preparation and I don't know how strict CxxWrap is with mixing versions.
Using master is probably not a good idea.

**Comment by fingolfin** [comment]
@benlorenz all good points of course. Of course even better would be if CxxWrap.jl simply would include the workaround, at least until a "proper" solution is found
