### ISSUE TITLE
Code blocks are too narrow

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/oscar-website#97]
And linebreaks are confusing. E.g. at https://rfourquet.github.io/oscar-website/install/ , section "Ubuntu 16.04 "Xenial": 

![codeblocks](https://user-images.githubusercontent.com/8462914/80085615-c069d900-8558-11ea-83c7-3e21926ccf77.png)

**Comment by fingolfin** [comment]
At least two options:
1. we could start to scroll horizontally if the line is too long
2. we could simply let the long line overflow...

Some suggestions for how to implement this e.g. here (found via some quick googling, I don't claim it's best ref, just some that seems to be helpful): https://css-tricks.com/considerations-styling-pre-tag/
